version: '3'
services:
  bare_seek: # The SEEK application
    #build: .

    image: fairdom/seek:1.14
    command: docker/entrypoint.sh
    restart: always
    environment:
      RAILS_ENV: production
    volumes:
      - seek-filestore:/seek/filestore
      - seek-cache:/seek/tmp/cache
    ports:
      - "3033:3000"

volumes:
  seek-filestore:
  seek-cache:
