apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\alain\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -v
    kompose.version: 1.31.2 (a92241f79)
  labels:
    io.kompose.service: bare-seek
  name: bare-seek
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bare-seek
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\alain\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -v
        kompose.version: 1.31.2 (a92241f79)
      labels:
        io.kompose.network/bare-seek-default: "true"
        io.kompose.service: bare-seek
    spec:
      containers:
        - args:
            - docker/entrypoint.sh
          env:
            - name: RAILS_ENV
              value: production
          image: fairdom/seek:1.14
          name: seek
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
          resources: 
            limits:
              memory: "6Gi"
              cpu: "1"
            requests:
              memory: "6Gi"
              cpu: "1"
          volumeMounts:
            - mountPath: /bare-seek/filestore
              name: bare-seek-filestore
            - mountPath: /bare-seek/tmp/cache
              name: bare-seek-cache
      restartPolicy: Always
      volumes:
        - name: bare-seek-filestore
          persistentVolumeClaim:
            claimName: bare-seek-filestore
        - name: bare-seek-cache
          persistentVolumeClaim:
            claimName: bare-seek-cache
status: {}
