---
title: "Backups and Security"
---

# Which data

One generally important aspect of Data Management and data usage is to know which data to store and how to store it. 

## Personal data

In many countries storage of personal information is strictly regulated. In the EU, storage of personal data can be done only with consent, must be accessible by the user, can be deleted upon request and can be stored only for a limited time.

TODO: Add links

When some research data is linked to person, it is advised to pseudonymize or to anonymize the data.

::: {.callout-important}
The limitation of data storage for personal information includes backups
:::

## Confidential data

## Passwords & keys

# Backups

Backups are an inherent - and maybe the most important - part of security, as they protect from mishaps as well as actual attacks. They are evidently not enough if a software has any kind of shared usage.
Any shared usage need some kind of security, not only public access. A good faith use of a software with the wrong privileges could have some bad consequences. Evidently such security starts with the software design and implementation, such as database constraints. This page will not speak about that.

::: {.callout-note}
Backups are for recoveries, public data should also be published in repositories.
:::

Backups tools -> versioning, monitoring, differential and incremental backups and automation. Using non-backup tools need some parameters and/or script to get some of these functions. Monitoring the backup is working will be extremely important ("silent death").

# Security

## Defence need to be always a success, attack need only one

One very important rule of security is that the attacker needs only one success. So it does not matter if many attempts are unsuccessful. They only need to try again. Thus defenders must adapt and monitor. It should be avoiding known vulnerabilies while trying to care for unknown ones.

## Aspects of security

By security in an information system, we consider every aspect allowing the right use of the information system (including, but not only, the protection of data):
Availability, integrity, confidentiality, trustworthiness, access control.
It is important to know which of these aspects are needed in the system to build. The possible threats are then coming from:
- the system users, not willingly doing any damage,
- malicious persons, who want to access data or program, to damage the infrastructure, to cheat, to annoy,
- malicious software, a software which will give a nuisance to other or abuse the resources (that can be unintentional), open the system to intrusions,
- one disaster, a simple electric break, one bad manipulation, a fire, …
It is very common that the regular users are gates for malicious persons. We speak here about social engineering: the weak point is the human-human relation. The famous Kevin Mitnick mostly used this system to intrude systems. A right information of the user is one
way to fight against this kind of problem.

A very wide overview of possible outrages and how to mitigate them is part of [Business Continuity Planning](https://en.wikipedia.org/wiki/Business_continuity_planning).

## Limits of security

Security in computer software is very much alike security in the real-life: if you want your house to be totally secure, you have to push a 3 meter high concrete wall around with automatic machine guns. Not fun, not neighbour-friendly and not inhabitant-friendly too. The same rule applies in software development: you just cannot have a totally secured system, as nothing will be usable then (or with much difficulties). The fact is that, like in the real life, the user must show some respect to other users and to the software architecture, and we must protect the system mostly from deviant users.
The problem is that, in computer world, all users are potentially deviant! You have to see the interface of the software as the public area of it: naturally, with many users, you can assume that they will try all, so you have to ensure that no dangerous parts are left in it. Doing so (part of the security by design), you remove the major part of potential thread from the users.

## General dispositions

Default user not root (or super user if Windows)

Careful with the paths and their access rights

Symbolic links

Database user, schema protections

difficult configurations and their possible issues (such as .htaccess or apache configuration in general)

Fail fast -> difference between errors where the application needs to/can contine and when it needs to stop.

???

## Surface of attack

About security, we will often speak about reducing the surface of attack. The surface of attack is the part of the system that can be accessed by an attacker. The more surface of attack, the more chances for an attacker to find a vulnerability. Thus, reducing the surface of attack is necessary for security. For instance, if you have a web application, you should not have any other service running on the same server that can be accessed from the outside. If you have a database, it should not be accessible from the outside, but only from the application. If you have a backup system, it should not be accessible from the outside, but only from the application and/or from a secure location.

## Firewall

A firewall is a software or hardware that blocks traffic that is not needed.

One aspect of a Firewall is to reduce the surface of attack by blocking all the traffic that is not needed. For instance, if you have a web application, you should only allow traffic on port 80 (HTTP) and 443 (HTTPS). The database should not be accessible from the outside, but only from the application. The backup system should not be accessible from the outside, but only from the application and/or from a secure location. 

But a firewall can also be used to block traffic from known malicious IP addresses or, if the software is not designed to be used by the public, to block all traffic from the outside and only allow traffic from a secure location (such as a VPN), while autorizing some external access by whitelisting some IP addresses.

## Protections against attacks

To review, expend and simplify. Extract Denial of Service/BruteForce and simple abuse from robots and agents.


There are many kinds of attacks, such as SQL injection, cross-site scripting, cross-site request forgery, brute force, denial of service. Some of them can be mitigated by the software design and implementation, such as using prepared statements for SQL queries, using a web application firewall, using a rate limiter, using a CAPTCHA, using a strong password policy, using two-factor authentication, using a VPN, using a firewall, using a backup system, using a monitoring system. Some of them can be mitigated by the user behavior, such as using a strong password, not sharing passwords, not clicking on suspicious links, not downloading suspicious files, not giving away personal information, not using public Wi-Fi for sensitive operations.
But some others are more difficult to mitigate, such as zero-day vulnerabilities, insider threats, social engineering, and at the extreme physical attacks (such as theft or sabotage).

Protecting against abuses is also difficult.

## Passwords and keys

Passwords are still the most common way to protect access to a system, but they are also the most vulnerable. They should be strong and unique, and should not be shared. They should not be written down or stored in plain text. To encourage users to use strong passwords, it is recommended to propose a password manager or a vault, that can generate strong passwords and store them securely. The application should also enforce strong passwords, and should not allow weak passwords. Allowing long passwords allow to use passphrases, that are easier to remember and can be very strong, they can be non-sensical sentences, so easy to remember but hard to guess, such as "TheCowBouBouBounceOnTheMoon!".
If supported, two-factor authentication should be used, as it adds an extra layer of security.

But one of the strongest way to propose an access is to use keys, that can be generated and stored securely, and can be easily revoked if needed. For instance, SSH keys are a very common way to access a server, and they are much more secure than passwords. They can be generated with a passphrase, that adds an extra layer of security.

Some authentication system can also use tokens (which are a kind of key), that can be generated and stored securely, and can be easily revoked if needed. For instance, API tokens are a very common way to access an API, and they are much more secure than having to regularly use an username and passwords.

Most of the time, the software will need to access some resources (such as a database) with a password or a key. In that case, it is important to store these credentials in a secure way, such as in an environment variable, in a configuration file with restricted access, or in a secret manager. They should never be stored in plain text in the code or in the configuration file.

Most Data Management platforms also support external authentication, such as LDAP or OAuth. OAuth is a very common way to allow users to authenticate with their existing credentials, such as Google or GitHub. It is also a secure way to authenticate, as it relies on the security of the external provider (assuming the user is following the provider's security practices, but if not it is probably a generalized practice and would be a problem anyway).

## What to never log, log levels

Log are incredibly useful and should be used for debugging purpose and for security (they are often the only way to detect a tentative of intrusion/code injection). 

For instance, it could be important to log all suspicious url paths are it might be a tentative of code injection, i.e. the attacker hoping that a mechanism in the code will execute a payload.

A simple example would be executing raw SQL queries:

* The URL subpath is /users/[name] where [name] is the name you want to look for.
* The code will then simply execute "SELECT * FROM users WHERE name=[name];"
* The attacker will use the URL subpath "/users/name";DROP%20TABLE%20admin;%20 --".
* The code will execute "SELECT * FROM users WHERE name="name";DROP TABLE admin; --"". The end "--" is to comment the closing quote so it does not raise an error.
* If the access right of the database is too permissible and an admin table exists, it will be dropped (but the example code is for illustration only, it might not work and in all cases it *should not work*).

This is a really well known and simple example and no modern web framework or API should allow such attacks nowadays. But the actual issue is with unknow vulnerability. Going back to this example, the web application should log something like:

```"2025-11-23_2:32:22 - Warning - incorrect characters in path: "/users/name";DROP%20TABLE%20admin;%20 --"```

And that would allow to check what was attempted.

But logs are also plain text and, if accessed by an attacker, will be easy to comprehend. As such, there are information that should never been logged, and some that should be carefully logged:

- username, password, keys, important DB table names (such as a users table used for login), should ideally never be written in a log file, even on DEBUG level and even on test. The reason for that is that everything that happen on test can happen on production. Amid a quick fix during an emergency, a test log entry can be forgiven and go to production. A fix on sensitive information can use the logs, but should be done in a very controlled way, without hurry, even during an emergency. A good way to proceed is to allow the log info only when needed, then switch it off (ideally remove the log entries) immediately after.
- 

## What to never store (or never in "reversible" format)

All kind of passwords should never be stored in a reversible format. If the password is needed for the software to work, it should be stored in an encrypted format, with a key that is not stored on the same system. If the password is only needed for authentication, it should be hashed with a strong hashing algorithm and a salt.

Any key, hash or token that can be used to access the system should be stored in an encrypted format, with a key that is not stored on the same system.

In most countries, the storage of personal data is restricted by law. In the EU, for instance, personal data can only be stored with consent, must be accessible by the user, can be deleted upon request and can be stored only for a limited time. Thus, if some research data is linked to person, it is advised to pseudonymize or to anonymize the data. Only the needed data should be stored, and only for the needed time.

::: {.callout-note}
The limitation of data storage for personal information includes backups.
:::

::: {.callout-note}
The exchange of personal data between institutions can only by done with an agreement and with the consent of the user. It is recommended to consult a data protection officer for that.
:::

## Know your infrastructure

## Deleting data